config/routes.rb
Rails.application.routes.draw do
  post 'signup', to: "signup#create"

  post 'sessions', to: "sessions#create"

  get 'sessions', to: "sessions#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Defines the landing page of the site
  root 'landing#index'

  # Defines admin pages
  get 'admin/', to: 'admin#admin_home'
  get 'admin/home', to: 'admin#admin_home', as: 'admin_home'
  get 'admin/settings', to: 'admin#admin_settings', as: 'admin_settings'
  post 'admin/settings/save', to: "admin#save"
  get 'admin/app_profile/:id(.:format)', to: 'admin#admin_app_profile', as: 'admin_app_profile'
  post 'admin/app_profile/editstatus', to: 'admin#edit_status'
  post 'admin/app_profile/deleteapp', to: 'admin#delete_application'
  get 'admin/courses', to: 'admin#admin_courses', as: 'admin_courses'
  post 'admin/courses/edittuition', to: 'admin#edit_tuition'
  post 'admin/courses/deletecourse', to: 'admin#delete_course'
  post 'admin/courses/addcourse', to: 'admin#add_course'


  # Defines student pages
  get 'student/', to: 'student#student_home'
  get 'student/home', to: 'student#student_home', as: 'student_home'
  get 'student/settings', to: 'student#student_settings', as: 'student_settings'
  post 'student/settings/save', to: "student#save"
  get 'student/profile', to: 'student#student_profile', as: 'student_profile'
  get 'student/profile/:id', to: 'student#student_profile_id', as: 'student_profile_id'
  post 'student/profile/addcourse', to: 'student#add_application'
  post 'student/profile/editcourse', to: 'student#edit_application'
  post 'student/profile/deletecourse', to: 'student#delete_application'
  get 'student/school_view/:id(.:format)', to: 'student#school_view', as: 'student_school_view'

end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
	before_action :check_if_student
def student_home
	@all_schools = School.order(:sname)
	if params[:search]!="" && params[:radio]=="school"
		@all_schools = School.select('school_id,sname, address').where("LOWER(sname) LIKE ? ", "%#{params[:search]}%" )
  	elsif params[:search]!="" && params[:radio]=="course"
  		@all_schools = Offer.joins('join schools ON offers.school_id = schools.school_id JOIN courses ON offers.course_offered_id = courses.course_id').select('schools.sname,schools.school_id,schools.address').where("LOWER(courses.course_name) LIKE ? ", "%#{params[:search]}%" )
  	elsif params[:search]=="" && params[:radio]==""
  		@all_schools = School.select('school_id,sname, address').where("LOWER(sname) LIKE ? ", "%#{params[:search]}%" )
  	else
    	@all_schools = School.order(:sname)
  	end
end
def student_profile
	@user_student = User.find(cookies[:userid])
	@stud_deets = Student.find(cookies[:userid])
	@apps = Apply.joins('join applications on applies.ref_no = applications.ref_no join courses on courses.course_id = applications.course_id join schools on applies.school_id = schools.school_id').select('applies.student_userid, schools.school_id, schools.sname, applies.ref_no, applies.is_received, courses.course_name').where(student_userid:cookies[:userid])
	@all_schools = School.order(:sname)
	@all_courses = Course.order(:course_name) 
	#need pa ng "where" clause kasi lahat lang ng inaapplyan ng student yung lalabas
	# @apps = Apply.joins('join applications on applies.ref_no = applications.ref_no join courses on courses.course_id = applications.course_id join schools on applies.school_id = schools.school_id').select('applies.student_userid, schools.school_id, schools.sname, applies.is_received, courses.course_name').where(student_userid:1)
end
def school_view
	@school = School.find(params[:id]) 
	@courses = Offer.joins('join courses on offers.course_offered_id = courses.course_id join schools on offers.school_id = schools.school_id').select('courses.course_name,
		courses.duration, courses.sector,courses.tuition_fee').where(school_id:params[:id])
end

def student_settings
	@user_student = User.find(cookies[:userid])
	#change constant to session id

end
def save
	@user_student = User.find(cookies[:userid])
	#change constant to session id
	@user_student.username = params[:username]
	@user_student.e_mail = params[:e_mail]
	@user_student.name = params[:name]
	@user_student.password = params[:password]
	@user_student.save
	flash[:notice] = "Settings saved"
	redirect_to student_settings_path
end
def add_application
	begin
		@course = Course.select('course_id').where(course_name: params[:course_name]).first
		@school = School.select('school_id').where(sname: params[:school]).first
		@application = Application.new(:course_id => @course.course_id)
		@application.save
		@apply = Apply.new(:student_userid => cookies[:userid], :school_id => @school.school_id, :ref_no => @application.ref_no, :is_received => 'No')
		@apply.save
		flash[:notice] = "Application added to database."
		redirect_to student_profile_path
	rescue
		flash[:error] = "Error adding application to database."
		redirect_to student_profile_path
	end
end

def edit_application
	begin
		@course = Course.select('course_id').where(course_name: params[:course_name]).first
		@application = Application.select('*').where(ref_no: params[:ref_no]).first
		@application.course_id = @course.course_id
		@application.save
		flash[:notice] = "Application edited successfully."
		redirect_to student_profile_path
	rescue
		flash[:error] = "Error editing application."
		redirect_to student_profile_path
	end
end

def delete_application
	begin
		@apply = Apply.where(ref_no: params[:reference_no]).delete_all
		@application = Application.where(ref_no: params[:reference_no]).delete_all
		flash[:notice] = "Application deleted."
		redirect_to student_profile_path
	rescue
		flash[:error] = "Error deleting application."
		redirect_to student_profile_path
	end
end

def check_if_student
	if !cookies.key?(:userid)
		redirect_to root_url
		return
	end
	@student = Student.where(student_userid: cookies[:userid])
	if @student.blank?
		@admin = Admin.where(admin_userid: cookies[:userid])
		if @admin.blank?
			redirect_to root_url
			return
		else
			redirect_to admin_home_path
			return
		end
	end
end

end

app/views/student/school_view.html.erb
<!--School Profile(User)-->
<%= render "layouts/usernavbar" %>
<header id="profile">
<div class="ui grid container">
    <div class="four wide column">
      <div class="ui card">
      <div class="image">
        <img src=<%=asset_path"school.jpg"%>>
      </div>
      <div class="content">
        <a class="header"><%= @school.sname %></a>
        <div class="description">
          <%= @school.email %><br>
          <%= @school.address %>
          <br>
          <%= @school.phone %>
        </div>
      </div>
    </div>
</div>
    <div class="twelve wide column">
    <h1 class="text">Courses Offered</h1>
    <div class="ui divider"></div>
    <table class="ui celled table">
  <thead>
    <tr>
      <th>Course</th>
      <th>Duration (hr)</th>
      <th>Sector</th>
      <th>Tuition Fee (Php)</th>
    </tr>
  </thead>
  <tbody>
    <% @courses.each do |course| %>
    <tr>
      <td><%=course.course_name%></td>
      <td><%=course.duration%></td>
      <td><%=course.sector%></td>
      <td><%=course.tuition_fee%></td>
    </tr>
    <%end%>
  </tbody>
</table>
  </div>
</div>

</header>

app/views/student/student_home.html.erb
<%= render "layouts/usernavbar" %>
<header id="home">
<div class="ui text container">
  <div class="title">
  <h1 class="header">Welcome to Online TESDA Application!</h1>
</div>
<br>
<%= form_tag(student_home_path, :method => "get", id: "search-form", class: "ui form") do %>
  <div class="field">
    <div class="ui action left icon input">
        <i class="search icon"></i>
        <%= text_field_tag :search, "", placeholder: "Search for ..."%>
         <%=  button_tag("Search", class: "ui button blue", type: "submit") %>
       
      </div>
  </div>

  <div class="inline fields">
      <div class="inline fields">
    <label for="fruit">Search by:</label>
    <div class="field">
      <div class="ui radio checkbox">
        <%= text_field_tag :radio, "", type:"radio", value:"school",tabindex:"0", class:"active", checked:"true"%>
        <%= label_tag(:"School") %>
      </div>
    </div>
    <div class="field">
      <div class="ui radio checkbox">
        <%= text_field_tag :radio, "", type:"radio", value:"course",tabindex:"0", class:"hidden"%>
        <%= label_tag(:"Course") %>
      </div>
    </div>
  </div>
</div>
  <% end %>

  <div class="ui raised segments">
    <% @all_schools.each do |school| %>
    <div class="ui padded segment">
      <div class="ui header"> <a href=<%=student_school_view_path(school.school_id)%>> <%= school.sname %></a></div>
      <p><%= school.address %></p>
    </div>
    <%end%>
  
  </div>

</div>
</header>

<script>
$(document).ready(function(){
$('.ui.radio.checkbox')
  .checkbox()
;
});
</script>

app/views/student/student_profile.html.erb
<!--My Applications (User)-->
<%= render "layouts/usernavbar" %>
<header id="profile">

<div class="ui grid container">
    <div class="four wide column">
      <div class="ui card">
      <div class="image">
        <img src=<%=asset_path"avatar.png"%>>
      </div>
      <div class="content">
        <a class="header"><%= @user_student.name%></a>
        <div class="meta">
          <span class="username">@<%= @user_student.username%></span>
        </div>
        <div class="description">
          <%= @user_student.e_mail%><br>
          <%= @stud_deets.birthdate%><br>
         <%= @stud_deets.address%><br>
         <%= @stud_deets.civil_status%><br>
        </div>
      </div>
    </div>
    <button class="fluid ui blue button" id="new-app"><i class="plus icon"></i>New Application</button>
</div>
<div class="twelve wide column">
  <% flash.each do |key, value| %>
            <% if key.eql? "error" %>
              <div class="ui negative message alert alert-<%= key %>"><%= value %></div>
            <% elsif key.eql? "notice" %>
              <div class="ui positive message alert alert-<%= key %>"><%= value %></div>
            <% flash.clear %>
            <% end %>
          <% end %>
  <h1 class="text">My Applications</h1>
  <div class="ui divider"></div>
    <table class="ui celled table">
  <thead>
    <tr>
      <th>School</th>
      <th>Course</th>
      <th>Received</th>
      <th>Options</th>
    </tr>
  </thead>
  <tbody>
    <% @apps.each do |app| %>
    <tr>
      <td><%= app.sname%></td>
      <td><%= app.course_name%></td>
      <% if app.is_received.eql? "Yes"%>
        <td class="positive"><i class="check circle icon"></i><%= app.is_received%></td>
      <% elsif app.is_received.eql? "No" %>
        <td class="warning"><i class="attention icon"></i><%= app.is_received%></td>
      <% end %>
      <%= form_tag(student_profile_deletecourse_path, method: "post", class: "ui form") do %> 
      <td><button type="button" class="ui small green button" name="edit_btn">
        <input type="hidden" name="ref_no[]" value="<%= app.ref_no %>" form="modal-edit-form"></input>
        Edit
      </button>
        <button class="ui small red button" action="submit" method="post">
        <input type="hidden" name="reference_no" value="<%= app.ref_no %>"></input>
        Cancel
        </button></td>
      <% end %>
    </tr>
    <%end%>
  </tbody>
</table>
  </div>
</div>

</header>
<div class="ui small modal">
  <i class="close icon"></i>
  <div class="header">
    New Application
  </div>
  <div class="content">
    <%= form_tag(student_profile_addcourse_path, method: "post", class: "ui form", id: "modal-add-form") do %>
      <div class="two fields">
        <div class="field">
            <label>School</label>
            <select class="ui search dropdown" name="school">
              <option value="">Select School</option>
               <% @all_schools.each do |school|%>
              <option value="<%=school.sname%>" ><%=school.sname%></option>
              <%end%>
            </select>
        </div>
        <div class="field">
          <label>Course</label>
          <select class="ui search dropdown" name="course_name">
            <option value="">Select Course</option>
            <% @all_courses.each do |course|%>
              <option value="<%=course.course_name%>"><%=course.course_name%></option>
              <%end%>
          </select>
        </div>
      </div>
  </div>
  <div class="actions">
    <button class="ui positive right labeled icon button" type="submit" form="modal-add-form">
      Add<i class="plus icon"></i>
    </button>
  </div>
  <% end %>
</div>
<div class="ui tiny modal">
  <i class="close icon"></i>
  <div class="header">
    Edit Course
  </div>
  <div class="content">
    <%= form_tag(student_profile_editcourse_path, method: "post", class: "ui form", id: "modal-edit-form") do %>
        <div class="field">
          <label>Course</label>
          <select class="ui search dropdown" action="" name="course_name">
            <option value="">Select Course</option>
            <% @all_courses.each do |course|%>
              <option value="<%=course.course_name%>"><%=course.course_name%></option>
              <%end%>
          </select>
        </div>
    <% end %>
  </div>
  <div class="actions">
    <button class="ui positive button" form="modal-edit-form" action="submit" method="post">
      Save
    </button>
    <button class="ui red button">
     Cancel
    </button>
  </div>
</div>
<script>
   $('#new-app').click(function(){
      $('.small.modal')
      .modal('show'); 
        $('select.dropdown')
  .dropdown()
;
   });
  $('button[name=edit_btn]').click(function(){
      $('.tiny.modal')
      .modal('show'); 
        $('select.dropdown')
  .dropdown()
;
   });

</script>

app/views/student/student_settings.html.erb
<%= render "layouts/usernavbar" %>
<header id="settings">
<div class="ui text container">
  <div class="title">
  <h1 class="header">Edit Settings</h1>
</div>
  <div class="ui divider"></div>
<%= form_tag(student_settings_save_path, method: "post", class: "ui form") do %>
<% flash.each do |key, value| %>
              <div class="ui positive message alert alert-<%= key %>"><%= value %></div>
              <% flash.clear %>
            <% end %>
    <div class="field">
    <%= label_tag(:"Username") %>
    <%= text_field_tag(:username, "", placeholder: "", value:@user_student.username ) %>
  </div>
  <div class="field">
     <%= label_tag(:"Email") %>
    <%= text_field_tag(:e_mail, "", placeholder: "", value:@user_student.e_mail ) %>
  </div>
    <div class="field">
    <%= label_tag(:"Name") %>
    <%= text_field_tag(:name, "", placeholder: "", value:@user_student.name ) %>
  </div>
  <div class="field">
    <%= label_tag(:"Password") %>
    <%= text_field_tag(:password, "", placeholder: "Type your new password here", type:"password") %>
  </div>
  <%= button_tag("Save", class: "ui button green", type: "submit") %>
  
  <% end %>
</form>
</div>
</div>