config/routes.rb
Rails.application.routes.draw do
  post 'signup', to: "signup#create"

  post 'sessions', to: "sessions#create"

  get 'sessions', to: "sessions#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Defines the landing page of the site
  root 'landing#index'

  # Defines admin pages
  get 'admin/', to: 'admin#admin_home'
  get 'admin/home', to: 'admin#admin_home', as: 'admin_home'
  get 'admin/settings', to: 'admin#admin_settings', as: 'admin_settings'
  post 'admin/settings/save', to: "admin#save"
  get 'admin/app_profile/:id(.:format)', to: 'admin#admin_app_profile', as: 'admin_app_profile'
  post 'admin/app_profile/editstatus', to: 'admin#edit_status'
  post 'admin/app_profile/deleteapp', to: 'admin#delete_application'
  get 'admin/courses', to: 'admin#admin_courses', as: 'admin_courses'
  post 'admin/courses/edittuition', to: 'admin#edit_tuition'
  post 'admin/courses/deletecourse', to: 'admin#delete_course'
  post 'admin/courses/addcourse', to: 'admin#add_course'


  # Defines student pages
  get 'student/', to: 'student#student_home'
  get 'student/home', to: 'student#student_home', as: 'student_home'
  get 'student/settings', to: 'student#student_settings', as: 'student_settings'
  post 'student/settings/save', to: "student#save"
  get 'student/profile', to: 'student#student_profile', as: 'student_profile'
  get 'student/profile/:id', to: 'student#student_profile_id', as: 'student_profile_id'
  post 'student/profile/addcourse', to: 'student#add_application'
  post 'student/profile/editcourse', to: 'student#edit_application'
  post 'student/profile/deletecourse', to: 'student#delete_application'
  get 'student/school_view/:id(.:format)', to: 'student#school_view', as: 'student_school_view'

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
	before_action :check_if_logged_in
	def index
		@all_schools = School.order(:sname)
	end

	def check_if_logged_in
		if !cookies.key?(:userid)
			return
		end
		@student = Student.where(student_userid: cookies[:userid])
		if @student.blank?
			@admin = Admin.where(admin_userid: cookies[:userid])
			if @admin.blank?
				return
			else
				redirect_to admin_home_path
			end
		else
			redirect_to student_home_path
		end
	end
end

app/views/landing/admin_appProfile.html.erb
<!--My Applications (User)-->
<%= render "layouts/adminnavbar" %>
<header id="profile">
<div class="ui grid container">
  <div class="four wide column">
      <div class="ui card">
      <div class="image">
        <img src="/assets/avatar.png">
      </div>
      <div class="content">
        <a class="header">Abby del Castillo</a>
        <div class="meta">
          <span class="username">@abbydc</span>
        </div>
        <div class="description">
          abby1097@gmail.com<br>
          Oct. 28, 1997<br>
          Rancho II, Marikina City<br>
          Single 
        </div>
      </div>
    </div>
</div>

<div class="twelve wide column">
<h1 class="text">Course Applications</h1>
<div class="ui divider"></div>
  <table class="ui celled table">
  <thead>
    <tr>
      <th>Course</th>
      <th>Current Status</th>
      <th>Option</th>
    </tr>
  </thead>
  <tbody>
    <tr>
     <td>Web Development I</td>
     <td class="negative"><i class="remove circle icon"></i>Rejected</td>
     <td><button class="ui small green button" name="edit-btn">Edit Status</button> 
      <button class="ui small red button">Delete</button></td>
    </tr>
    <tr>
      <td>Web Development II</td>
      <td class="positive"><i class="check circle icon"></i>Accepted</td>
      <td><button class="ui small green button" name="edit-btn">Edit Status</button> <button class="ui small red button">Delete</button></td>
    </tr>
    <tr>
      <td>Web Development III</td>
      <td class="warning"><i class="attention icon"></i>Pending</td>
      <td><button class="ui small green button" name="edit-btn">Edit Status</button><button class="ui small red button">Delete</button></td>
    </tr>
  </tbody>
  </table>
</div>





<div class="ui tiny modal">
  <i class="close icon"></i>
  <div class="header">
    Edit Status
  </div>
 <div class="content">
    <form class="ui form">
        <div class="field">
          <label>Status</label>
          <select class="ui search dropdown">
            <option value="">Select Status</option>
            <option value="1">Accepted</option>
            <option value="2">Rejected</option>
          </select>
        </div>
    </form>
  </div>
  <div class="actions">
    <div class="ui positive button">
      Save
    </div>
    <div class="ui red button">
     Cancel
    </div>
  </div>
</div>
<script>
   $('#new-app').click(function(){
      $('.small.modal')
      .modal('show'); 
        $('select.dropdown')
  .dropdown()
;
   });
  $('button[name=edit-btn]').click(function(){
      $('.tiny.modal')
      .modal('show'); 
        $('select.dropdown')
  .dropdown()
;
   });

</script>

app/views/landing/admin_courses.html.erb
<!--My Applications (User)-->
<%= render "layouts/adminnavbar" %>
<header id="profile">
<div class="ui grid container">
    <div class="four wide column">
     <div class="ui card">
      <div class="image">
        <img src="/assets/school.jpg">
      </div>
      <div class="content">
        <a class="header">Marikina Science High School</a>
        <div class="description">
          mshs@gmail.com<br>
          Chanyungco St., Sta.Elena, Marikina City
          <br>
          997-7852
        </div>
      </div>
    </div>
    <button class="fluid ui blue button" id="new-app"><i class="plus icon"></i>Add Course</button>
</div>

<div class="twelve wide column">
  <h1 class="text">Courses Offered</h1>
  <div class="ui divider"></div>
    <table class="ui celled table">
  <thead>
    <tr>
      <th>Course</th>
      <th>Sector</th>
      <th>Tuition Fee</th>
      <th>Options</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Web Development I</td>
      <td>IT</td>
      <td>1200</td>
      <td><button class="ui small green button" name="edit-btn">Edit</button> <button class="ui small red button">Remove</button></td>
    </tr>
    <tr>
      <td>Web Development II</td>
      <td>IT</td>
      <td>1200</td>
      <td><button class="ui small green button" name="edit-btn">Edit</button> <button class="ui small red button">Remove</button></td>
    </tr>
     <tr>
      <td>Web Development III</td>
      <td>IT</td>
      <td>1200</td>
      <td><button class="ui small green button" name="edit-btn">Edit</button> <button class="ui small red button">Remove</button></td>
    </tr>
  </tbody>
</table>
  </div>
</div>

</header>
<div class="ui small modal">
  <i class="close icon"></i>
  <div class="header">
    Add Course
  </div>
  <div class="content">
    <form class="ui form">
      <div class="one field">
        <div class="field">
            <label>Course</label>
            <select class="ui search dropdown">
              <option value="">Select School</option>
              <option value="1">Web Development I</option>
              <option value="2">Web Development II</option>
              <option value="3">Web Development III</option>
            </select>
        </div>
      </div>
    </form>
  </div>
  <div class="actions">
    <div class="ui positive right labeled icon button">
      Add<i class="plus icon"></i>
    </div>
    <div class="ui red button">
     Cancel
    </div>
  </div>
</div>

<div class="ui tiny modal">
  <i class="close icon"></i>
  <div class="header">
    Edit Course
  </div>
  <div class="content">
    <form class="ui form">
        <div class="field">
          <label>Tuition Fee</label>
          <input class="prompt" type="text" placeholder="Enter new tuition fee...">
        </div>
    </form>
  </div>
  <div class="actions">
    <div class="ui positive button">
      Save
    </div>
    <div class="ui red button">
     Cancel
    </div>
  </div>
</div>
<script>
   $('#new-app').click(function(){
      $('.small.modal')
      .modal('show'); 
        $('select.dropdown')
  .dropdown()
;
   });
  $('button[name=edit-btn]').click(function(){
      $('.tiny.modal')
      .modal('show'); 
        $('select.dropdown')
  .dropdown()
;
   });

</script>

app/views/landing/admin_settings.html.erb
<%= render "layouts/usernavbar" %>
<header id="settings">
<div class="ui text container">
  <div class="title">
  <h1 class="header">Edit School Details</h1>
</div>
<div class="ui divider"></div>
<%= form_tag(admin_settings_save_path, method: "post", class: "ui form") do %>
<% flash.each do |key, value| %>
<div class="ui positive message alert alert-<%= key %>"><%= value %></div>
    <% flash.clear %>
<% end %>
    <div class="field">
    <%= label_tag(:"School Name") %>
    <%= text_field_tag(:sname, "", placeholder: "", value:@school.sname ) %>
  </div>
  <div class="field">
        <%= label_tag(:"Email") %>
    <%= text_field_tag(:email, "", placeholder: "", value:@school.email ) %>
  </div>
    <div class="field">
    <%= label_tag(:"Address") %>
    <%= text_field_tag(:address, "", placeholder: "", value:@school.address ) %>
  </div>
  <div class="field">
    <%= label_tag(:"Contact Number") %>
    <%= text_field_tag(:phone, "", placeholder: "", value:@school.phone ) %>
  </div>
   <%= button_tag("Save", class: "ui button green", type: "submit") %>
 <% end %>
</form>
</div>
</div>

app/views/landing/index.html.erb
<header id="landing">
<div class="ui grid container">
    <div class="eight wide column">
          <div class="landing-page relative-position">
            <div class="ui center aligned container">
              <img src=<%=asset_path"otapp_Index.png"%> height="200px" alt="">
              <p class="semibold paragraph">OTapp is an online TESDA application system for aspiring students. The goal of this website is to aid people who would like to enroll to TESDA by making the application process more efficient through doing it online. Same quality of education for a less hassle application experience.</p>
            </div>
          </div>
        </div>
        <!--crucial!! data tabs of log in and sign up changed because of gray part-->
        <div class="eight wide column"  name="tab-menu">
          <div class="ui top attached tabular menu">
            <a class="item active" data-tab="first"><h3>Sign In</h3></a>
            <a class="item" data-tab="second" onClick="signUp()"><h3>Register</h3></a>
          </div>
          <div class="ui bottom attached tab segment active" data-tab="first">
            <%= form_tag(sessions_path, method: "post", class: "ui form") do %>
            <% flash.each do |key, value| %>
              <div class="ui negative message alert alert-<%= key %>"><%= value %></div>
              <% flash.clear %>
            <% end %>
          <!--     <div class="inline fields">
                <label for="fruit">Sign in as:</label>
                <div class="field">
                  <div class="ui radio checkbox">
                    <input type="radio" name="search" checked="" tabindex="0" class="hidden">
                    <label>Admin</label>
                  </div>
                </div>
                <div class="field">
                  <div class="ui radio checkbox">
                    <input type="radio" name="search" tabindex="0" class="hidden">
                    <label>Student</label>
                  </div>
                </div>
              </div> -->
              <div class="field">
                <%= label_tag(:"Email") %>
                <%= text_field_tag(:e_mail, "", placeholder: "johndoe@gmail.com") %>
              </div>
              <div class="field">
                <%= label_tag("Password") %>
                <%= password_field_tag(:password, "", placeholder: "password") %>
              </div>
              <%= button_tag("Sign in", class: "fluid ui green button pull-right", type: "submit") %>
            <% end %>
          </div>
          <div class="ui bottom attached tab segment" data-tab="second">
                  
              <div class="sign-up-form form-padding">
              <div class="fluid ui buttons">
  <button class="ui teal button"  onClick="signUpAdmin()">Admin</button>
  <div class="or"></div>
  <button class="ui blue button"  onClick="signUpStudent()">Student</button>
</div>
              </div>
              <div class="form-padding-signup" style="display: none;">
                <div class="signup-admin" style="display: none;">
                  <p style="text-align: right;">Admin</p>
                  <%= form_tag(signup_path, method: "post", class: "ui form") do %>
                      <input type="hidden" value="Admin" name="type" id="admintype" />
                      <div class="field">
                        <%= label_tag("Full Name") %>
                        <%= text_field_tag(:name, "", placeholder: "John Doe") %>
                      </div>
                      <div class="field">
                        <%= label_tag("School") %>
                          <div class="ui compact menu">
                          <select class="ui fluid search dropdown" name="school_name">
                              <option value="">Select School</option>
                                <% @all_schools.each do |school| %>
                                <option value="<%= school.sname %>" > <%= school.sname %></option>
                                <%end%>
                          </select>
                          <!-- <div class = "text"> "Select School"</div>
                          <i class="dropdown icon"></i>
                          <div class="menu"> 
                           <% @all_schools.each do |school| %>
                           <div class = "item"> <% school.sname %></div>
                           <%end%>
                          </div>
                        </select> -->
                      </div>
                      <div class="field">
                        <%= label_tag("School Position") %>
                        <%= text_field_tag(:school_pos, "", placeholder: "Principal") %>
                      </div>
                      <div class="field">
                        <%= label_tag("Username") %>
                        <%= text_field_tag(:username, "", placeholder: "johndoe") %>
                      </div>
                      <div class="field">
                        <%= label_tag("Email") %>
                        <%= text_field_tag(:e_mail, "", placeholder: "johndoe@gmail.com") %>
                      </div>
                      <div class="field">
                        <%= label_tag("Password") %>
                        <%= password_field_tag(:password, "", placeholder: "password", id: "AtxtPassword") %>
                      </div>
                      <div class="field">
                        <%= label_tag("Confirm password") %>
                        <%= password_field_tag(:password_conf, "", placeholder: "password", id: "AtxtConfirmPassword") %>
                      </div>
                    <div class="center">
                      <button class="fluid ui blue button" onclick="return AdminValidate()">Create Account</button>
                    </div>
                  <% end %>
                </div>
              </div>
                <div class="signup-student" style="display: none;">
                    <p style="text-align: right;"> Student
                    <%= form_tag(signup_path, method: "post", class: "ui form") do %>
                      <input type="hidden" value="Student" name="type" id="studenttype" />
                      <div class="fields">
                        <div class="ten wide field">
                          <div class="field">
                            <%= label_tag("Full Name") %>
                            <%= text_field_tag(:name, "", placeholder: "John Doe") %>
                          </div>
                        </div>
                        <div class="six wide field">
                          <div class="field">
                            <%= label_tag("Birthdate") %>
                            <%= text_field_tag(:birthdate, "", placeholder: "1997-10-18") %>
                          </div>
                        </div>
                      </div>
                      <div class="fields">
                        <div class="ten wide field">                      
                          <div class="field">
                              <%= label_tag("Address") %>
                              <%= text_field_tag(:address, "", placeholder: "#30 Kalayaan Dormitory, Diliman, Quezon City") %>
                          </div>
                        </div>
                        <div class="six wide field">
                          <div class="field">
                            <%= label_tag("Civil Status") %>
                            <%= text_field_tag(:civil_status, "", placeholder: "Single") %>
                          </div>
                        </div>
                      </div>
                      <div class="field">
                        <%= label_tag("Username") %>
                        <%= text_field_tag(:username, "", placeholder: "johndoe") %>
                      </div>
                      <div class="field">
                        <%= label_tag("Email") %>
                        <%= text_field_tag(:e_mail, "", placeholder: "johndoe@gmail.com") %>
                      </div>
                      <div class="field">
                        <%= label_tag("Password") %>
                        <%= password_field_tag(:password, "", placeholder: "password", id: "txtPassword") %>
                      </div>
                      <div class="field">
                        <%= label_tag("Confirm password") %>
                        <%= password_field_tag(:password_conf, "", placeholder: "password", id: "txtConfirmPassword") %>
                      </div>
                      <div class="center">
                      <button class="fluid ui blue button" onclick="return UserValidate()">Create Account</button>
                      </div>
                <% end %>
              </div>
          
          </div>
        </div>
</header>
<script>
$(document).ready(function() {
  $('.menu .item').tab();
});
function signUpAdmin() {
  $('.signup-admin').css("display", "block");
  $('.signup-student').css("display", "none");
  $('.sign-up-form').css("display", "none");
  $('.form-padding-signup').css("display", "block");
}

function signUpStudent(){
  $('.signup-student').css("display", "block");
  $('.signup-admin').css("display", "none");
  $('.sign-up-form').css("display", "none");
  $('.form-padding-signup').css("display", "block"); 
}

function signUp(){
  $('.sign-up-form').css("display", "block");
  $('.signup-admin').css("display", "none");
  $('.signup-student').css("display", "none");
  $('.form-padding-signup').css("display", "none");
}
 function UserValidate() {
        var password = document.getElementById("txtPassword").value;
        var confirmPassword = document.getElementById("txtConfirmPassword").value;
        if (password != confirmPassword) {
            alert("Passwords do not match.");
            return false;
        }
        return true;
    }
 function AdminValidate() {
        var password = document.getElementById("AtxtPassword").value;
        var confirmPassword = document.getElementById("AtxtConfirmPassword").value;
        if (password != confirmPassword) {
            alert("Passwords do not match.");
            return false;
        }
        return true;
    }

   $('#new-app').click(function(){
      $('.small.modal')
      .modal('show'); 
        $('select.dropdown')
  .dropdown()
;
   });

        $('select.dropdown')
  .dropdown()
;
  

</script>

app/views/landing/settings.html.erb
<%= render "layouts/usernavbar" %>
<header id="settings">
<div class="ui text container">
  <div class="title">
  <h1 class="header">Edit Settings</h1>
</div>
  <div class="ui divider"></div>
<form class="ui form">
    <div class="field">
    <label>Username</label>
    <input type="text" name="last-name" placeholder="">
  </div>
  <div class="field">
    <label>Email</label>
    <input type="text" name="last-name" placeholder="">
  </div>
    <div class="field">
    <label>Name</label>
    <input type="text" name="last-name" placeholder="">
  </div>
  <div class="field">
    <label>Password</label>
    <input type="text" name="first-name" placeholder="">
  </div>
  <button class="ui button green" type="submit">Save</button>
</form>
</div>
</div>

app/views/landing/user_profile.html.erb
<!--My Applications (User)-->
<%= render "layouts/usernavbar" %>
<header id="profile">
<div class="ui grid container">
    <div class="four wide column">
      <div class="ui card">
      <div class="image">
        <img src="/assets/avatar.png">
      </div>
      <div class="content">
        <a class="header">Abby del Castillo</a>
        <div class="meta">
          <span class="username">@abbydc</span>
        </div>
        <div class="description">
          abby1097@gmail.com<br>
          Oct. 28, 1997<br>
          Rancho II, Marikina City<br>
        </div>
      </div>
    </div>
    <button class="fluid ui blue button" id="new-app"><i class="plus icon"></i>New Application</button>
</div>
<div class="twelve wide column">
  <h1 class="text">My Applications</h1>
  <div class="ui divider"></div>
    <table class="ui celled table">
  <thead>
    <tr>
      <th>School</th>
      <th>Course</th>
      <th>Status</th>
      <th>Options</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>UP Diliman</td>
      <td>Web Development I</td>
      <td class="warning"><i class="attention icon"></i>Pending</td>
      <td><button class="ui small green button" name="edit-btn">Edit</button> <button class="ui small red button">Cancel</button></td>
    </tr>
    <tr>
      <td>Marikina Polytechnic School</td>
      <td>Culinary Arts II</td>
      <td class="positive"><i class="check circle icon"></i>Accepted</td>
            <td><button class="ui small green button" name="edit-btn">Edit</button> <button class="ui small red button">Cancel</button></td>
    </tr>
     <tr>
      <td>Marikina Science School</td>
      <td>Basic Mechanics</td>
      <td class="negative"><i class="remove circle icon"></i>Rejected</td>
            <td><button class="ui small green button" name="edit-btn">Edit</button> <button class="ui small red button">Cancel</button></td>
    </tr>
  </tbody>
</table>
  </div>
</div>

</header>
<div class="ui small modal">
  <i class="close icon"></i>
  <div class="header">
    New Application
  </div>
  <div class="content">
    <form class="ui form">
      <div class="two fields">
        <div class="field">
            <label>School</label>
            <select class="ui search dropdown">
              <option value="">Select School</option>
              <option value="1">Marikina Science High School</option>
              <option value="2">Marikina Polytechnic School</option>
              <option value="3">UP Diliman</option>
            </select>
        </div>
        <div class="field">
          <label>Course</label>
          <select class="ui search dropdown">
            <option value="">Select Course</option>
            <option value="1">Basic Mechanics</option>
            <option value="2">Culinary Arts II</option>
            <option value="3">Web Development I</option>
          </select>
        </div>
      </div>
    </form>
  </div>
  <div class="actions">
    <div class="ui positive right labeled icon button">
      Add<i class="plus icon"></i>
    </div>
    <div class="ui red button">
     Cancel
    </div>
  </div>
</div>
<div class="ui tiny modal">
  <i class="close icon"></i>
  <div class="header">
    Edit Course
  </div>
  <div class="content">
    <form class="ui form">
        <div class="field">
          <label>Course</label>
          <select class="ui search dropdown">
            <option value="">Select Course</option>
            <option value="1">Basic Mechanics</option>
            <option value="2">Culinary Arts II</option>
            <option value="3">Web Development I</option>
          </select>
        </div>
    </form>
  </div>
  <div class="actions">
    <div class="ui positive button">
      Save
    </div>
    <div class="ui red button">
     Cancel
    </div>
  </div>
</div>
<script>
   $('#new-app').click(function(){
      $('.small.modal')
      .modal('show'); 
        $('select.dropdown')
  .dropdown()
;
   });
  $('button[name=edit-btn]').click(function(){
      $('.tiny.modal')
      .modal('show'); 
        $('select.dropdown')
  .dropdown()
;
   });

</script>