config/routes.rb
Rails.application.routes.draw do
  post 'signup', to: "signup#create"

  post 'sessions', to: "sessions#create"

  get 'sessions', to: "sessions#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Defines the landing page of the site
  root 'landing#index'

  # Defines admin pages
  get 'admin/', to: 'admin#admin_home'
  get 'admin/home', to: 'admin#admin_home', as: 'admin_home'
  get 'admin/settings', to: 'admin#admin_settings', as: 'admin_settings'
  post 'admin/settings/save', to: "admin#save"
  get 'admin/app_profile/:id(.:format)', to: 'admin#admin_app_profile', as: 'admin_app_profile'
  post 'admin/app_profile/editstatus', to: 'admin#edit_status'
  post 'admin/app_profile/deleteapp', to: 'admin#delete_application'
  get 'admin/courses', to: 'admin#admin_courses', as: 'admin_courses'
  post 'admin/courses/edittuition', to: 'admin#edit_tuition'
  post 'admin/courses/deletecourse', to: 'admin#delete_course'
  post 'admin/courses/addcourse', to: 'admin#add_course'


  # Defines student pages
  get 'student/', to: 'student#student_home'
  get 'student/home', to: 'student#student_home', as: 'student_home'
  get 'student/settings', to: 'student#student_settings', as: 'student_settings'
  post 'student/settings/save', to: "student#save"
  get 'student/profile', to: 'student#student_profile', as: 'student_profile'
  get 'student/profile/:id', to: 'student#student_profile_id', as: 'student_profile_id'
  post 'student/profile/addcourse', to: 'student#add_application'
  post 'student/profile/editcourse', to: 'student#edit_application'
  post 'student/profile/deletecourse', to: 'student#delete_application'
  get 'student/school_view/:id(.:format)', to: 'student#school_view', as: 'student_school_view'

end

app/views/admin/admin_app_profile.html.erb
<!--My Applications (User)-->
<%= render "layouts/adminnavbar" %>
<header id="profile">
<div class="ui grid container">
  <div class="four wide column">
      <div class="ui card">
      <div class="image">
        <img src=<%=asset_path"avatar.png"%>>
      </div>
      <div class="content">
        <a class="header"><%= @applicant.name %></a>
        <div class="meta">
          <span class="username">@<%= @applicant.username %></span>
        </div>
        <div class="description">
          <%= @applicant.e_mail %><br>
          <%= @app_deets.birthdate %><br>
          <%= @app_deets.address %><br>
          <%= @app_deets.civil_status %>
        </div>
      </div>
    </div>
</div>

<div class="twelve wide column">
  <% flash.each do |key, value| %>
            <% if key.eql? "error" %>
              <div class="ui negative message alert alert-<%= key %>"><%= value %></div>
            <% elsif key.eql? "notice" %>
              <div class="ui positive message alert alert-<%= key %>"><%= value %></div>
            <% flash.clear %>
            <% end %>
          <% end %>
<h1 class="text">Course Applications</h1>
<div class="ui divider"></div>
  <table class="ui celled table">
  <thead>
    <tr>
      <th>Course</th>
      <th>Received</th>
      <th>Option</th>
    </tr>
  </thead>
  <tbody>
    <% @apps.each do |app| %>
    <tr>
      <td><%= app.course_name%></td>
      <% if app.is_received.eql? "Yes"%>
        <td class="positive"><i class="check circle icon"></i><%= app.is_received%></td>
      <% elsif app.is_received.eql? "No" %>
        <td class="warning"><i class="attention icon"></i><%= app.is_received%></td>
      <% end %>
      <%= form_tag(admin_app_profile_deleteapp_path, method: "post", class: "ui form") do %> 
      <td><button type="button" class="ui small green button" name="edit_btn">
        <input type="hidden" name="ref_no" value="<%= app.ref_no %>" form="modal-edit-form"></input>
        Edit Status
      </button> 
      <button class="ui small red button">
      <input type="hidden" name="ref_no" value="<%= app.ref_no %>">
      Delete
      </button></td>
    </tr>
    <%end%>
    <%end%>
  </tbody>
  </table>
</div>

<div class="ui mini modal">
  <i class="close icon"></i>
  <div class="header">
    Edit Status
  </div>
 <div class="content">
    <%= form_tag(admin_app_profile_editstatus_path, method: "post", class: "ui form", id: "modal-edit-form") do %>
        <div class="field">
          <label>Received</label>
          <select class="ui search dropdown" name="is_received">
            <option value="">Select Received Status</option>
            <option value="Yes">Yes</option>
            <option value="No">No</option>
          </select>
        </div>
     <% end %>
  </div>
  <div class="actions">
    <button class="ui positive button" form="modal-edit-form" action="submit" method="post">
      Save
    </div>
  </div>
</div>
<script>
   $('#new-app').click(function(){
      $('.small.modal')
      .modal('show'); 
        $('select.dropdown')
  .dropdown()
;
   });
  $('button[name=edit_btn]').click(function(){
      $('.mini.modal')
      .modal('show'); 
        $('select.dropdown')
  .dropdown()
;
   });

</script>

app/views/admin/admin_courses.html.erb
<!--My Applications (User)-->
<%= render "layouts/adminnavbar" %>
<header id="profile">
<div class="ui grid container">
    <div class="four wide column">
     <div class="ui card">
      <div class="image">
        <img src=<%=asset_path"school.jpg"%> >
      </div>
      <div class="content">
        <a class="header"><%= @school.sname %></a>
          <div class="description">
           <%= @school.email %>
           <br>
            <%= @school.address %>
            <br>
            <%= @school.phone %>
          </div>
      </div>
    </div>
    <button class="fluid ui blue button" id="new-app"><i class="plus icon"></i>Add Course</button>
  </div>


<div class="twelve wide column">
  <% flash.each do |key, value| %>
            <% if key.eql? "error" %>
              <div class="ui negative message alert alert-<%= key %>"><%= value %></div>
            <% elsif key.eql? "notice" %>
              <div class="ui positive message alert alert-<%= key %>"><%= value %></div>
            <% flash.clear %>
            <% end %>
          <% end %>
  <h1 class="text">Courses Offered</h1>
  <div class="ui divider"></div>
    <table class="ui celled table">
  <thead>
    <tr>
      <th>Course</th>
      <th>Sector</th>
      <th>Tuition Fee</th>
      <th>Options</th>
    </tr>
  </thead>
  <tbody>
    <% @courses_offered.each do |course|%>
    <tr>
      <td><%= course.course_name%></td>
      <td><%= course.sector%></td>
      <td><%= course.tuition_fee%></td>
      <td>
        <%= form_tag(admin_courses_deletecourse_path, method: "post", class: "ui form") do %>
        <button type="button" class="ui small green button" name="edit-btn">
          <input type="hidden" name="course_offered_no[]" value="<%= course.course_offered_id %>" form="modal-edit-form"></input>
        Edit
        </button> 
        <button class="ui small red button" action="submit" method="post">
        <input type="hidden" name="course_offered_no" value="<%=course.course_offered_id %>"></input>
        Remove
        </button> </td>
        <%end%>
    </tr>
    <%end%>
  </tbody>
</table>
  </div>
</div>
</div>
</header>
<div class="ui small modal">
  <i class="close icon"></i>
  <div class="header">
    Add Course
  </div>
  <div class="content">
    <%= form_tag(admin_courses_addcourse_path, method: "post", class: "ui form", id: "modal-add-form") do %>
      <div class="one field">
        <div class="field">
            <label>Course</label>
            <select class="ui search dropdown" name="course_name">
              <option value="">Select Course</option>
              <% @all_courses.each do |course| %>
              <option  value="<%= course.course_id %>"><%= course.course_name %></option>
              <%end%>
            </select>
        </div>
      </div>
    <%end%>
  </div>
  <div class="actions">
    <button class="ui positive right labeled icon button" type="submit" form="modal-add-form">
      Add<i class="plus icon"></i>
    </button>
  </div>
</div>

<div class="ui tiny modal">
  <i class="close icon"></i>
  <div class="header">
    Edit Course
  </div>
  <div class="content">
    <%= form_tag(admin_courses_edittuition_path, method: "post", class: "ui form" ,id: "modal-edit-form") do %>
        <div class="field">
          <%= label_tag(:"Tuition Fee") %>
          <%= text_field_tag(:tuition_fee, "", placeholder: "Enter new tuition fee...", class: "prompt") %>
        </div>
    <% end %>
  </div>
  <div class="actions">
  <button class="ui positive button" form="modal-edit-form" action="submit" method="post">
      Save
    </button>
  </div>
</div>
<script>
   $('#new-app').click(function(){
      $('.small.modal')
      .modal('show'); 
        $('select.dropdown')
  .dropdown()
;
   });
  $('button[name=edit-btn]').click(function(){
      $('.tiny.modal')
      .modal('show'); 
        $('select.dropdown')
  .dropdown()
;
   });

</script>

app/views/admin/admin_home.html.erb
<!--My Applications (User)-->
<%= render "layouts/adminnavbar" %>
<header id="profile">



<div class="ui grid container">
    <div class="four wide column">
      <div class="ui card">
        <div class="image">
          <img src=<%=asset_path"school.jpg"%>>
        </div>
        <div class="content">
          <a class="header"><%= @school.sname %></a>
          <div class="description">
           <%= @school.email %>
           <br>
            <%= @school.address %>
            <br>
            <%= @school.phone %>
          </div>
        </div>
      </div>
    </div>


<div class="twelve wide column">
   <h1>Welcome <%= @school_admin.school_pos %>!</h1>
   <div class="ui divider"></div>
     <%= form_tag(admin_home_path, :method => "get", id: "search-form", class: "ui form") do %>
    <div class="field">
    <div class="ui action left icon input">
        <i class="search icon"></i>
        <%= text_field_tag :search, "", placeholder: "Search for ..."%>
         <%=  button_tag("Search", class: "ui button blue", type: "submit") %>
      </div>
    </div>
    <div class="inline fields">
        <div class="inline fields">
      <label for="fruit">Search by:</label>
      <div class="field">
        <div class="ui radio checkbox">
           <%= text_field_tag :radio, "", type:"radio", value:"name",tabindex:"0", class:"active", checked:"true"%>
        <%= label_tag(:"Applicants") %>
        </div>
      </div>
      <div class="field">
        <div class="ui radio checkbox">
          <%= text_field_tag :radio, "", type:"radio", value:"course",tabindex:"0", class:"hidden"%>
        <%= label_tag(:"Course") %>
        </div>
      </div>
    </div>
  </div>
<% end %>
    <div class="ui raised segments">
      <% @applicants.each do |app|%>
      <div class="ui padded segment">
        <div class="ui header"> <a href=<%=admin_app_profile_path(app.userid)%>><%= app.name %></a></div>
      </div>
      <%end%>
    </div>
  
  </div>
</div>
  </header>

</div>

<script>
$(document).ready(function(){
$('.ui.radio.checkbox')
  .checkbox()
;
});

</script>

app/views/admin/admin_settings.html.erb
<%= render "layouts/adminnavbar" %>
<header id="settings">
<div class="ui text container">
  <div class="title">
  <h1 class="header">Edit School Details</h1>
  </div>
  <div class="ui divider"></div>
  <%= form_tag(admin_settings_save_path, method: "post", class: "ui form") do %>
  <% flash.each do |key, value| %>
              <div class="ui positive message alert alert-<%= key %>"><%= value %></div>
              <% flash.clear %>
            <% end %>
  <div class="field">
    <%= label_tag(:"School Name") %>
    <%= text_field_tag(:sname, "", placeholder: "", value:@school.sname) %>
  </div>
  <div class="field">
    <%= label_tag(:"Email") %>
    <%= text_field_tag(:e_mail, "", placeholder: "", value:@school.email) %>
  </div>
  <div class="field">
    <%= label_tag(:"Address") %>
    <%= text_field_tag(:address, "", placeholder: "", value:@school.address)%>
  </div>
  <div class="field">
    <%= label_tag(:"Contact Number") %>
    <%= text_field_tag(:phone, "", placeholder: "", value:@school.phone) %>
  </div>
  <%= hidden_field :school_id, :value => @temp.school_id %>
  <%= button_tag("Save", class: "ui button green", type: "submit") %>
  <% end %>

</div>
</div>