config/routes.rb
Rails.application.routes.draw do
  post 'signup', to: "signup#create"

  post 'sessions', to: "sessions#create"

  get 'sessions', to: "sessions#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Defines the landing page of the site
  root 'landing#index'

  # Defines admin pages
  get 'admin/', to: 'admin#admin_home'
  get 'admin/home', to: 'admin#admin_home', as: 'admin_home'
  get 'admin/settings', to: 'admin#admin_settings', as: 'admin_settings'
  post 'admin/settings/save', to: "admin#save"
  get 'admin/app_profile/:id(.:format)', to: 'admin#admin_app_profile', as: 'admin_app_profile'
  post 'admin/app_profile/editstatus', to: 'admin#edit_status'
  post 'admin/app_profile/deleteapp', to: 'admin#delete_application'
  get 'admin/courses', to: 'admin#admin_courses', as: 'admin_courses'
  post 'admin/courses/edittuition', to: 'admin#edit_tuition'
  post 'admin/courses/deletecourse', to: 'admin#delete_course'
  post 'admin/courses/addcourse', to: 'admin#add_course'


  # Defines student pages
  get 'student/', to: 'student#student_home'
  get 'student/home', to: 'student#student_home', as: 'student_home'
  get 'student/settings', to: 'student#student_settings', as: 'student_settings'
  post 'student/settings/save', to: "student#save"
  get 'student/profile', to: 'student#student_profile', as: 'student_profile'
  get 'student/profile/:id', to: 'student#student_profile_id', as: 'student_profile_id'
  post 'student/profile/addcourse', to: 'student#add_application'
  post 'student/profile/editcourse', to: 'student#edit_application'
  post 'student/profile/deletecourse', to: 'student#delete_application'
  get 'student/school_view/:id(.:format)', to: 'student#school_view', as: 'student_school_view'

end

app/views/layouts/_adminnavbar.html.erb
<header id="header">
  <link rel="shortcut icon" src="/assets/logo_Dbq_icon.ico"/>
  <div class="ui banner container">
    
      <img src=<%=asset_path"otapp_logo.png"%> alt="" style="max-height:70px;">
    
  </div>
  <div class="nav">
    <div class="ui container">
      <div class="left-nav">
                <a href=<%=admin_home_path"" %> class="item">
          <i class="home icon"></i>
          Home
        </a>
      </div>
      <div class="right-nav">
        <div class="field">
        <a href=<%=admin_courses_path"" %> class="item">
          <i class="file text outline icon"></i>
          Courses
        </a>
        <a href=<%=admin_settings_path"" %> class="item">
          <i class="settings icon"></i>
          Settings
        </a>
        <a href=<%=sessions_path %> class="item">
          <i class="sign out icon"></i>
          Logout
        </a>
        </div>
      </div>
    </div>
  </div>
</header>
<div class="header-placeholder"></div>

app/views/layouts/_usernavbar.html.erb
<header id="header">
  <div class="ui banner container">
      <img src=<%=asset_path"otapp_logo.png"%> alt="" style="max-height:70px;">
  </div>
  <div class="nav">
    <div class="ui container">
      <div class="left-nav">
                <a href=<%=student_home_path"" %> class="item">
          <i class="home icon"></i>
          Home
        </a>
      </div>
      <div class="right-nav">
        <div class="field">
        <a href=<%=student_profile_path"" %>  class="item">
          <i class="file text outline icon"></i>
          My Applications
        </a>
        <a href=<%=student_settings_path"" %>  class="item">
          <i class="settings icon"></i>
          Settings
        </a>
        <a href=<%=sessions_path %> class="item">
          <i class="sign out icon"></i>
          Logout
        </a>
        </div>
      </div>
    </div>
  </div>
</header>
<div class="header-placeholder"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OTapp</title>
    <link rel="icon" type="image/ico" href=<%=asset_path"favicon.ico"%>>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>